
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'

config-version: 2

# This setting configures which "profile" dbt uses for this project. For dbt Cloud,
# you can leave this as "default"
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["dbt_demo_dir/models"]
analysis-paths: ["dbt_demo_dir/analysis"] 
test-paths: ["dbt_demo_dir/tests"]
data-paths: ["dbt_demo_dir/data"]
macro-paths: ["dbt_demo_dir/macros"]
log-path: dbt_demo_dir/logs
modules-path: dbt_demo_dir/dbt_modules

target-path: "dbt_demo_dir/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "dbt_demo_dir/target"
    - "dbt_demo_dir/dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: table
